# Dockerfile

FROM golang:1.5.0
MAINTAINER SUPINF Inc.

RUN go get -u gopkg.in/xmlpath.v2
RUN go get -u github.com/justinas/alice
RUN go get -u github.com/garyburd/redigo/redis
RUN go get -u gopkg.in/throttled/throttled.v1
RUN go get -u github.com/robfig/cron
RUN go get -u github.com/kurrik/oauth1a
RUN go get -u github.com/aws/aws-sdk-go/service/dynamodb
